@startuml
title AQUA-DRIFT Domain Classes
hide methods
skinparam classAttributeIconSize 0

class ScenarioConfig {
  observerLimit: 1..100
  maxSlantRangeYd
  maxObservationSeconds: 10800
  dopplerIntervalSeconds: 1
  smoothingWindowSeconds
  presenceProbabilityPct
}
class TargetMotionConfig {
  desiredHdgDeg
  desiredThroughWaterSpeedKt
  desiredDepthFt
  hdgRateDegPerSec
  speedRateKtPerSec
  depthRateFtPerSec
}
class CurrentFieldConfig {
  referencePosition
  baseVelocity
  gradientPerNm[3][3]
}
class SourceFrequencyConfig {
  constantFrequencyHz
  sharedTimeInvariantBiasHz
}
class ObserverState {
  observerId
  tick
  exactPosition
  exactDepthFt
  status
}
class DopplerObservation {
  observerId
  tick
  observedFrequencyHz
  recognizedFrequencyHz
  relativeSpeedKt
  slantRangeYd
}
class TrackEstimate {
  mode
  tick
  observabilityStatus
  currentPosition [optional]
  presenceRegion
}
class PresenceRegion {
  probabilityPct
  rangeOnlyComponents[*]
  disconnected
}

ScenarioConfig *-- TargetMotionConfig
ScenarioConfig *-- CurrentFieldConfig
ScenarioConfig *-- SourceFrequencyConfig
ObserverState --> DopplerObservation
DopplerObservation --> TrackEstimate
TrackEstimate *-- PresenceRegion
@enduml
